#!/bin/bash
echo "============================================"
echo "   System Information Tool v1.0"
echo "   CSE 324 - OS Lab Project"
echo "============================================"
echo ""
echo "--- System Details ---"
echo "Hostname  : $(hostname)"
echo "OS        : $(uname -o 2>/dev/null || echo 'N/A')"
echo "Kernel    : $(uname -r)"
echo "Arch      : $(uname -m)"
echo "Uptime    : $(uptime -p 2>/dev/null || uptime)"
echo ""
echo "--- User Info ---"
echo "User      : $(whoami)"
echo "Home      : $HOME"
echo "Shell     : $SHELL"
echo ""
echo "--- Hardware ---"
echo "CPU       : $(grep -m1 'model name' /proc/cpuinfo 2>/dev/null | cut -d: -f2 | xargs || echo 'N/A')"
echo "RAM Total : $(free -h 2>/dev/null | awk '/Mem:/{print $2}' || echo 'N/A')"
echo "RAM Used  : $(free -h 2>/dev/null | awk '/Mem:/{print $3}' || echo 'N/A')"
echo ""
echo "--- Disk Usage ---"
df -h / 2>/dev/null | tail -1 | awk '{printf "Disk Used : %s / %s (%s)\n", $3, $2, $5}'
echo ""
echo "--- Network ---"
echo "IP Addr   : $(hostname -I 2>/dev/null | awk '{print $1}' || echo 'N/A')"
echo ""
echo "============================================"
echo "  System info collection complete!"
echo "============================================"
